services:
  orcaslicer:
    image: ghcr.io/riddix/orcaslicer:latest
    container_name: orcaslicer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # Intel iGPU settings
      - DRINODE=/dev/dri/renderD128
      - DRI_NODE=/dev/dri/renderD128
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: 2gb
    restart: unless-stopped
